animation = matrix

# Format string for clock in top right corner (see strftime specification). Example: %c
clock = null

bigclock = true

asterisk = ?

clear_password = false

vi_mode = false

# The `fg` and `bg` color settings take a digit 0-8 corresponding to:
#define TB_DEFAULT 0x00
#define TB_BLACK   0x01
#define TB_RED     0x02
#define TB_GREEN   0x03
#define TB_YELLOW  0x04
#define TB_BLUE    0x05
#define TB_MAGENTA 0x06
#define TB_CYAN    0x07
#define TB_WHITE   0x08
#
# Setting both to zero makes `bg` black and `fg` white. To set the actual color palette you are encouraged to use another tool
# such as [mkinitcpio-colors](https://github.com/evanpurkhiser/mkinitcpio-colors). Note that the color palette defined with
# `mkinitcpio-colors` takes 16 colors (0-15), only values 0-8 are valid for `ly` config and these values do not correspond
# exactly. For instance, in defining palettes with `mkinitcpio-colors` the order is black, dark red, dark green, brown, dark
# blue, dark purple, dark cyan, light gray, dark gray, bright red, bright green, yellow, bright blue, bright purple, bright
# cyan, and white, indexed in that order 0 through 15. For example, the color defined for white (indexed at 15 in the mkinitcpio
# config) will be used by `ly` for `fg = 8`.

# Background color id
bg = 0

# Foreground color id
fg = 8

# Border color
border_fg = 8

# Title to show at the top of the main box
box_title = null

# Initial text to show on the info line (Defaults to hostname)
initial_info_text = null

# Blank main box background
# Setting to false will make it transparent
blank_box = true

hide_borders = false

margin_box_h = 2
margin_box_v = 1

input_len = 34

max_desktop_len = 100
max_login_len = 255
max_password_len = 255

default_input = login

load = true

save = true

hide_key_hints = false

shutdown_key = F1
restart_key = F2
sleep_key = F3

shutdown_cmd = systemctl halt
restart_cmd = systemctl reboot

sleep_cmd = systemctl suspend

lang = en

tty = 2

# Console path
console_dev = /dev/console

path = /sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin

min_refresh_delta = 5

numlock = false

service_name = ly
term_reset_cmd = /usr/bin/tput reset
term_restore_cursor_cmd = /usr/bin/tput cnorm
mcookie_cmd = /usr/bin/mcookie
wayland_cmd = /etc/ly/wsetup.sh
waylandsessions = /usr/share/wayland-sessions
