#!/bin/sh

# Custom Keymaps
riverctl map normal Super C spawn foot
riverctl map normal Super W spawn firefox
riverctl map normal Super D spawn fuzzel
riverctl map normal Super Print spawn "grim && notify-send -t 2000 'Screenshot taken'"

riverctl map normal Super Q close
riverctl map normal Super+Shift Q exit
#

# Blaot
riverctl keyboard-layout tr
riverctl focus-follows-cursor normal
#

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super Right focus-view right
riverctl map normal Super Left focus-view left
riverctl map normal Super Up focus-view up
riverctl map normal Super Down focus-view down

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack

riverctl map normal Super+Shift Right swap right
riverctl map normal Super+Shift Left swap left
riverctl map normal Super+Shift Up swap up
riverctl map normal Super+Shift Down swap down

# Super+Return to bump the focused view to the top of the layout stack
riverctl map normal Super Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super Add send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super Subtract send-layout-cmd rivertile "main-ratio +0.05"

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    riverctl map normal Super $i set-focused-tags $tags
    riverctl map normal Super+Shift $i set-view-tags $tags

done

riverctl map normal Super Space toggle-float
riverctl map normal Super F toggle-fullscreen

for mode in normal locked
do
    riverctl map $mode None XF86Eject spawn 'eject -T'

    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
    riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

riverctl background-color 0x002b36
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75

riverctl set-repeat 30 300

riverctl rule-add -app-id 'float*' -title 'foo' float

riverctl rule-add -app-id "bar" csd

riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &

riverctl spawn "waybar"
riverctl spawn "foot"
riverctl spawn "dunst"
